version: '3'

services:
  app_rober:
    build: rober
    mem_reservation: 512m #pueden usar tambien limit para la memoria
    ports:
      - "8080:8080"
    environment: 
      DB_URL: jdbc:mysql://rober:33306/DB_RecursosHumanos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PSW: 123456
    restart: always
    depends_on:
      rober:
        condition: service_healthy 
  rober:
    image: mysql:8.0.26 
    ports:
      - "3306:33306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: DB_RecursosHumanos 
    restart: always 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
